from typing import Protocol, Dict, Any, Optional, List


class IBaseRepository(Protocol):
    def _to_mongo_doc(self, data: Dict[str, Any]) -> Dict[str, Any]: ...

    def _from_mongo_doc(
        self, doc: Optional[Dict[str, Any]]
    ) -> Optional[Dict[str, Any]]: ...

    async def create(self, data: Dict[str, Any]) -> str: ...

    async def find_by_id(self, id_: str) -> Optional[Dict[str, Any]]: ...

    async def find_all(
        self, filters: Dict[str, Any], skip: int, limit: int
    ) -> List[Dict[str, Any]]: ...

    async def find_one(self, filters: Dict[str, Any]) -> Optional[Dict[str, Any]]: ...

    async def update(self, id_: str, updates: Dict[str, Any]) -> bool: ...

    async def delete(self, id_: str) -> bool: ...

    async def exists(self, id_: str) -> bool: ...

    async def count(self, filters: Dict[str, Any] = None) -> int: ...
